# Numpy



In [1]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
# Criando um array de 1 dimensão
uma_dim = np.array([1,2,3,4])

In [3]:
type(uma_dim)

numpy.ndarray

In [4]:
# Qtde dimensões do array.
uma_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
duas_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Qtde dimensões do array.
duas_dim.ndim

2

In [7]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.02050409, 0.47600762],
       [0.08180898, 0.84120183],
       [0.90440854, 0.55568124],
       [0.00250477, 0.5593936 ],
       [0.23480711, 0.90791872]])

In [8]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Cria um array com valores zerado de 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays X Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [11]:
# Criando uma lista em Python.
lista = [1,2,3]

In [12]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [13]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [14]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [15]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [16]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [17]:
# Faz o calculo usando as listas
(pesos / (altura ** 2))

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [19]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [20]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [21]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

In [22]:
a * 2 

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

# Atributos e Métodos Úteis 

 Métodos disponíveis (digite o . pressione tab)
 
duas_dim. pressione tab

In [23]:
duas_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# Retorna a forma do array no formato linhas e colunas.
duas_dim.shape

(2, 3)

In [25]:
# Retorna a quantidade de dimensões.
duas_dim.ndim

2

In [26]:
# Imprimindo o valor máximo do array.
duas_dim.max()

6

In [27]:
# Imprimindo o valor mínimo.
duas_dim.min()

1

In [28]:
# Imprimindo o valor médio de todos os valores do array.
duas_dim.mean()

3.5

In [29]:
# Imprimindo o desvio padrão.
duas_dim.std()

1.707825127659933

In [30]:
# Tipo do array
duas_dim.dtype

dtype('int32')

In [31]:
# Tamanho do array
duas_dim.size

6

In [32]:
# mostra a quantidade
duas_dim.itemsize

4

In [33]:
# Somando todos os elementos do array.
duas_dim.sum()

21

#  Transformando Arrays

In [34]:
# Gera a Transposta da Matriz (Linha -> coluna)
duas_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
# Transforma em uma matriz de uma linha.
# É muito comum em bibliotecas como scikit-learn e Keras
duas_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [36]:
tree = np.random.random((5,3))

In [37]:
tree.shape

(5, 3)

In [38]:
tree

array([[0.20446715, 0.68457272, 0.43151313],
       [0.11746141, 0.06895666, 0.12927372],
       [0.62415023, 0.09427237, 0.19272199],
       [0.28835888, 0.94326206, 0.54897191],
       [0.93817365, 0.13014744, 0.63978278]])

In [39]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.20446715, 0.68457272, 0.43151313, 0.11746141, 0.06895666],
       [0.12927372, 0.62415023, 0.09427237, 0.19272199, 0.28835888],
       [0.94326206, 0.54897191, 0.93817365, 0.13014744, 0.63978278]])

In [40]:
tree.reshape(-1)

array([0.20446715, 0.68457272, 0.43151313, 0.11746141, 0.06895666,
       0.12927372, 0.62415023, 0.09427237, 0.19272199, 0.28835888,
       0.94326206, 0.54897191, 0.93817365, 0.13014744, 0.63978278])

In [41]:
t=tree.reshape(1,15)
t

array([[0.20446715, 0.68457272, 0.43151313, 0.11746141, 0.06895666,
        0.12927372, 0.62415023, 0.09427237, 0.19272199, 0.28835888,
        0.94326206, 0.54897191, 0.93817365, 0.13014744, 0.63978278]])

In [42]:
# Adicionando elementos a um array, transformando em um array de 1 linha
duas_dim = np.insert(duas_dim,0,10)

In [43]:
duas_dim

array([10,  1,  2,  3,  4,  5,  6])

In [44]:
# Apagando o elemento da primeira posição do array.
duas_dim = np.delete(duas_dim,[0])

In [45]:
duas_dim

array([1, 2, 3, 4, 5, 6])

In [46]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",duas_dim, delimiter=',')